info:
    app:
        description: This application fetches all the connections of a user
        name: Social Media Connections Application
        version: 1.0
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
            base-path: '/admin'
    info:
        env:
            enabled: true

logging:
    level:
        #        root: DEBUG, changing root level of logging
        com:
            example:
                socialMedia: TRACE #changing root level of our application
    #Saving the logs
    file:
        name: logger.log
    #Customizing the logs how to be saved
    pattern:
        file: '%d{yyyy-mm-dd} [%level] %c{1.} [%t] %m%n'

server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fitFusionDB
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
#Color Coding
    output:
        ansi:
            enabled: always