version: '3.7'
#Application we want to install in docker[ prometheus, grafana ]
services:
  prometheus:
    image: prom/prometheus:v2.35.0 #Application
    container_name: prometheus # where the project installs
    volumes: #Location to get configuration of this application
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: #default port
      - 9090:9090

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
